### ISSUE TITLE
MSBuild interpreting /p flag incorrectly

### ISSUE THREAD

**Issue by kcxt** [barisates/dotnet-core-gitlab-ci-cd-settings#1]
Hi,

Seem to be having an issue that nobody else on the internet has encountered...

```
$ dotnet test /p:CollectCoverage=true
MSBUILD : error MSB1009: Project file does not exist.
Switch: p:CollectCoverage=true
```

This happens from within the solution and within the test project. Specifying either csproj gives the same error:

```
$ dotnet test /p:CollectCoverage=true MyProject/MyProject.csproj
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Sunrise/Sunrise.csproj

For switch syntax, type "MSBuild -help"
```

And same when specifying the test project file.

I think I'm missing something simple but I'm absolutely stumped, running just `dotnet test` has no issues.

**Comment by barisates** [comment]
Hi,

To use the **/p:CollectCoverage=true** parameter, you need to add the **coverlet.msbuild** package to your test project.

See the link below
[https://github.com/barisates/dotnet-core-gitlab-ci-cd-settings#coverlet](https://github.com/barisates/dotnet-core-gitlab-ci-cd-settings#coverlet)

**Comment by kcxt** [comment]
Hi thanks for getting back, I have definitely installed the package in my test project :D

Here's my test .csproj if that's helpful.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="2.9.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="junitxml.testlogger" Version="2.1.32" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyProject\MyProject.csproj" />
  </ItemGroup>

</Project>
```

**Comment by kcxt** [comment]
https://github.com/coverlet-coverage/coverlet/issues/206

Bash is funky. Resolved by using `-p` instead of `/p`

**Comment by gimlichael** [comment]
> [coverlet-coverage/coverlet#206](https://github.com/coverlet-coverage/coverlet/issues/206)
> 
> Bash is funky. Resolved by using `-p` instead of `/p`

Thanks - this got me in the right direction. Oddly enough, the forward slash works perfectly fine in Ubuntu - but not in Windows when using bash (uses shell Git for Windows). Just in case someone finds themselves wondering like me from GitHub Actions :-)

> The default shell on non-Windows platforms with a fallback to sh. When specifying a bash shell on Windows, the bash shell included with Git for Windows is used.
